# Generated by Django 4.2.4 on 2023-10-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_alter_variant_product'),
        ('wishlist', '0003_remove_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variant.variant'),
        ),
    ]
