# Generated by Django 4.2.4 on 2023-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('brand_description', models.TextField(blank=True, max_length=300)),
                ('brand_image', models.ImageField(upload_to='photos/brand')),
                ('is_availiable', models.BooleanField(default=True)),
            ],
        ),
    ]
