# Generated by Django 4.2.4 on 2023-09-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='copon_code',
            new_name='Coupon_code',
        ),
    ]
