# Generated by Django 4.2.2 on 2023-08-20 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_user_token_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
