# Generated by Django 4.2.2 on 2023-08-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_secret',
        ),
    ]
