# Generated by Django 4.2.2 on 2023-08-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
