# Generated by Django 4.2.2 on 2023-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, max_length=300)),
                ('category_image', models.ImageField(blank=True, upload_to='photos/categories')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
