# Generated by Django 4.2.4 on 2023-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
