# Generated by Django 4.2.2 on 2023-09-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_address_name_address_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
