# Generated by Django 4.2.2 on 2023-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_pre_images_productimage_pr_images_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='cart.Cart_item', to='product.product'),
        ),
    ]
