# Generated by Django 4.2.4 on 2023-09-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_alter_variant_product'),
        ('cart', '0006_remove_cart_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variant.variant'),
        ),
    ]
