# Generated by Django 4.2.4 on 2023-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
