# Generated by Django 4.2.4 on 2023-09-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='product',
        ),
    ]
