# Generated by Django 4.2.4 on 2023-09-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_alter_variant_product'),
        ('orders', '0006_remove_order_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variant.variant'),
        ),
    ]
